---
title: "Scorched"
author: "Yuan Tien"
date: "4/11/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm( list= ls())

#Load PITF dataset
library(haven)
library(tidyverse)

setwd("/Users/yuantien/Desktop/CW_project/Data")

PITF <- read_dta("PITF Global Model Replication Data 121709.dta")

#Create name - code list to help determine the country in exclusionary ideology dataset
ccode_country <- PITF %>%
  select(sftgcode, sftgname)

ccode_country <- ccode_country[!duplicated(ccode_country$sftgcode),] #remove duplicate

ccode_country <- rename(ccode_country, "SCODE" = sftgcode, "country" = sftgname) 
```


```{r}
library(readxl)
exclude <- read_xls("ELCv2018.xls")
exclude <- exclude %>% left_join(ccode_country, by = "SCODE")

unique(exclude$SCODE[ which (is.na(exclude$country) == T) ])

exclude[exclude$SCODE == "ANG" , 5] <- "Angola"
exclude[exclude$SCODE == "AZE" , 5] <- "Azerbaijan"
exclude[exclude$SCODE == "BOS" , 5] <- "Bosnia and Herzegovina"
exclude[exclude$SCODE == "CAP" , 5] <- "Cape Verde"
exclude[exclude$SCODE == "DJI" , 5] <- "Djibouti"
exclude[exclude$SCODE == "ERI" , 5] <- "Eritrea"
exclude[exclude$SCODE == "ETM" , 5] <- "East Timor"
exclude[exclude$SCODE == "GMY" , 5] <- "Germany"
exclude[exclude$SCODE == "GRG" , 5] <- "Georgia"
exclude[exclude$SCODE == "KOS" , 5] <- "Kosovo"
exclude[exclude$SCODE == "LUX" , 5] <- "Luxembourg"
exclude[exclude$SCODE == "MAC" , 5] <- "Macedonia"
exclude[exclude$SCODE == "MLD" , 5] <- "Moldova"
exclude[exclude$SCODE == "SDN" , 5] <- NA
exclude[exclude$SCODE == "SER" , 5] <- "Serbia"
exclude[exclude$SCODE == "SSU" , 5] <- NA
exclude[exclude$SCODE == "SUR" , 5] <- "Suriname"
exclude[exclude$SCODE == "TAJ" , 5] <- "Tajikistan"
exclude[exclude$SCODE == "TKM" , 5] <- "Turkmenistan"
exclude[exclude$SCODE == "UKG" , 5] <- "United Kingdom"
exclude[exclude$SCODE == "USR" , 5] <- NA
exclude[exclude$SCODE == "UZB" , 5] <- "Uzbekistan"
```

```{r}
length ( unique(exclude$SCODE) ) #179 unique countries

exclude %>%
  filter(ELITI == 1) %>%
  distinct(SCODE) #70 countries have exclusionary ideology at some point of the time 

exclude %>%
  filter(YEAR == 2018, ELITI == 1) %>%
  distinct(country) 

```

```{r}
scor <- read_dta("Stanton+--+Violence+and+Restraint+in+Civil+War+--+Replication+Data.dta")

#prepare the data for merging
scor$country <- scor$government

scor$country[str_detect(scor$government, "Afghan") == T] <- "Afghanistan"  
scor$country[str_detect(scor$government, "Cambo") == T]  <- "Cambodia"
scor$country[str_detect(scor$government, "Chad") == T]   <- "Chad"
scor$country[str_detect(scor$government, "Brazzaville") == T] <- "Congo-Brazzaville"
scor$country[str_detect(scor$government, "Somalia") == T] <- "Somalia"

#before I merge exclude into scor, I need to mutate startyr-1 , startyr-2, startyr-3, startyr-4, startyr-5 to indicate 5 year time in which the gov could have exclusionary ideology. Later, I shall merge by 5 different year. Lastly, create a dummy indicating "had exclusionary ideology in recent years (5) )

scor <- scor %>%
  mutate(lag1yr = startyr -1, lag2yr = startyr -2, lag3yr = startyr -3, lag4yr = startyr -4, lag5yr = startyr -5) 

write_csv(scor, file = "scor.csv")
```

```{r}
#merge lag value of exclusion ideology project
scor_exc <- scor %>%
  left_join(exclude, by = c("lag1yr" = "YEAR", "country")) 

#now the data is prepared
```

Dependent variable: scorched earth campaign dummy
Independent var.  : exclusionary ideology dummy

```{r}
library(stargazer)

scor_exc <- as.data.frame(scor_exc) # Don't forget this!

stargazer(scor_exc[c("gscorched", "ELITI", "logpcgdp", "polity", "logtrade", "igo", "pro2ratification")], type = "latex", digits = 2, 
          title = "Table 1: Descriptive Statistics",
          covariate.labels=c("scorched earth campaign", "exclusionary ideology", "log GDP per capita", "polity score", "log trade involvement", "number of IGO joined", "ratification of Additional Protocol(II)"),
          out = "Descriptive Statistics.tex")

```


```{r}
#getOption("na.action") #Check what is the default methods in glm to deal with NA
#Note that my default setting for glm is na.omit, which use complete cases only. 

scor_exc %>%
  select(gscorched, ELITI, logpcgdp, polity, logtrade, igo, pro2ratification, g5massacre) %>%
  apply(., 2, function(x) sum(is.na(x)))  #Get a sense of how many NAs are in the variables

m1 <- glm(formula = gscorched ~ ELITI, family = binomial(link = "probit"), data = scor_exc)
m2 <- glm(formula = gscorched ~ ELITI + logpcgdp + polity, 
            family = binomial(link = "probit"), data = scor_exc)

m3 <- glm (formula = gscorched ~ ELITI + logtrade + igo + pro2ratification, 
            family = binomial(link = "probit"), data = scor_exc)

m4 <- glm(formula = gscorched ~ ELITI + logpcgdp + polity + logtrade + igo + pro2ratification, 
            family = binomial(link = "probit"), data = scor_exc)

which (colnames(scor_exc) == "pro2ratification")  #32, 91, 44, 65, 78, 79, 81)

stargazer(m1, m2, m3, m4, type = "latex", 
          title = "Table 2: Base Results",
          dep.var.labels = "Scorched earth campaign",
          covariate.labels = c("exclusionary ideology", "log GDP per capita", "polity score", "log trade involvement", "number of IGO joined", "ratification of Additional Protocol(II)"),
          out = "models.tex")
```

Average marginal effect

```{r}
library(margins)
library(mfx)

margin1 <- probitmfx(formula = gscorched ~ ELITI, data = scor_exc)$mfxest
margin2 <- probitmfx(formula = gscorched ~ ELITI + logpcgdp + polity, data = scor_exc)$mfxest
margin3 <- probitmfx(formula = gscorched ~ ELITI + logtrade + igo + pro2ratification, data = scor_exc)$mfxest
margin4 <- probitmfx(formula = gscorched ~ ELITI + logpcgdp + polity + logtrade + igo + pro2ratification, data = scor_exc)$mfxest

stargazer(m1, m2, m3, m4, type = "latex",
          title = "Table 3: Marginal Effect",
          coef =  list(margin1[,1], margin2[,1], margin3[,1], margin4[,1]), 
          se   =  list(margin1[,2], margin2[,2], margin3[,2], margin4[,2]),
          covariate.labels=c("exclusionary ideology", "log GDP per capita", "polity score", "log trade involvement", "number of IGO joined", "ratification of Additional Protocol(II)"),
          out  = "marginal.tex"
          )

```

Robustness Check 

1. check using "having excluding ideology for the previous 3 years"
```{r}
scor_exc <- rename(scor_exc, "lag1eip" = ELITI)

scor_exc <- scor_exc %>%
  left_join(exclude, by = c("lag2yr" = "YEAR", "country")) 

scor_exc <- rename(scor_exc, "lag2eip" = ELITI)

scor_exc <- scor_exc %>%
  left_join(exclude, by = c("lag3yr" = "YEAR", "country")) %>%
  rename("lag3eip" = ELITI)

scor_exc2 <- scor_exc %>%
  mutate(threeyr = rowSums ( dplyr::select (., lag1eip, lag2eip, lag3eip), na.rm = TRUE)) 

scor_exc <- scor_exc %>% rename("ELITI" = lag3eip) #return it to original name

scor_exc2$three_yr_dum <- ifelse (scor_exc2$threeyr > 0, 1, 0)

P <- scor_exc2 %>% dplyr::select(lag1eip, lag2eip, lag3eip, threeyr, three_yr_dum)
head(P) #check if the mutate works properly

#Now the data is prepared for this robustness check
```

```{r}
rob1 <- glm(formula = gscorched ~ three_yr_dum, family = binomial(link = "probit"), data = scor_exc2)
rob2 <- glm(formula = gscorched ~ three_yr_dum + logpcgdp + polity, 
            family = binomial(link = "probit"), data = scor_exc2)

rob3 <- glm (formula = gscorched ~ three_yr_dum + logtrade + igo + pro2ratification, 
            family = binomial(link = "probit"), data = scor_exc2)

rob4 <- glm(formula = gscorched ~ three_yr_dum + logpcgdp + polity + logtrade + igo + pro2ratification, 
            family = binomial(link = "probit"), data = scor_exc2)

stargazer(rob1, rob2, rob3, rob4, type = "latex", 
          title = "Table 4: Having exclusionary ideology for the last three years before conflict onset",
          dep.var.labels = "Scorched earth campaign",
          covariate.labels = c("exclusionary ideology 3years", "log GDP per capita", "polity score", "log trade involvement", "number of IGO joined", "ratification of Additional Protocol(II)"),
          out = "three_check.tex")

```

Robust EPR

```{r}
epr1 <- glm(formula = gscorched ~ ginclusive, family = binomial(link = "probit"), data = scor_exc2)
epr2 <- glm(formula = gscorched ~ ginclusive + logpcgdp + polity, 
            family = binomial(link = "probit"), data = scor_exc2)

epr3 <- glm (formula = gscorched ~ ginclusive + logtrade + igo + pro2ratification, 
            family = binomial(link = "probit"), data = scor_exc2)

epr4 <- glm(formula = gscorched ~ ginclusive + logpcgdp + polity + logtrade + igo + pro2ratification, 
            family = binomial(link = "probit"), data = scor_exc2)

stargazer(epr1, epr2, epr3, epr4, type = "latex", 
          title = "Table 5: EPR inclusive government",
          dep.var.labels = "Scorched earth campaign",
          covariate.labels = c("inclusive government", "log GDP per capita", "polity score", "log trade involvement", "number of IGO joined", "ratification of Additional Protocol(II)"),
          out = "EPR_check.tex")
```